name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"coverage"
    - name: Codecov      
      uses: codecov/codecov-action@v2.1.0
      with:        
        token: 43c789a4-4740-43e5-b632-c6c34e1269f6        
        directory: publish        
        flags: unittests        
        fail_ci_if_error: true        
        # move_coverage_to_trash: # optional
